#ifndef __HW_MEMMAP__
#define __HW_MEMMAP__

#define __DRIVERLIB_MSP430FR5XX_6XX_FAMILY__
//*****************************************************************************
//
// Include device specific header file
//
//*****************************************************************************
#include <msp430.h>

#ifndef __AUTOGENERATED__
#include "msp430fr5xx_6xxgeneric.h"
#endif

#include "stdint.h"
#include "stdbool.h"

//*****************************************************************************
//
// SUCCESS and FAILURE for API return value
//
//*****************************************************************************
#define MSP430_STATUS_SUCCESS 0x01
#define MSP430_STATUS_FAILURE 0x00

//*****************************************************************************
//
// Macro for enabling assert statements for debugging
//
//*****************************************************************************
#define NDEBUG

//*****************************************************************************
//
// Macros for hardware access
//
//*****************************************************************************

extern uint8_t hwMemmap_memory[65536];

#define HWREG8(x) (*((uint8_t *)(&hwMemmap_memory[x])))
#define HWREG16(x) (*((uint16_t *)(&hwMemmap_memory[x])))
#define HWREG32(x) (*((uint32_t *)(&hwMemmap_memory[x])))

#endif // #ifndef __HW_MEMMAP__
